version: 2

updates:
  # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
  - package-ecosystem: gitsubmodule
    schedule:
      interval: "daily"
    directory: /
    commit-message:
        prefix: "Auto-updated submodule references"
