name: Build CodeQL Queries 

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install CodeQL
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh extension install github/gh-codeql
          gh codeql pack download "codeql/${{ matrix.language }}-queries"

      - name: Compile Queries
        run: |
          gh codeql query compile --warnings=error --search-path=./codeql --additional-packs=./codeql/ ./${{ matrix.language }}/

      - name: Compile / Check Suites
        run: |
          for suite in ./${{ matrix.language }}/suites/*.qls ; do
            echo " >> $suite"
            gh codeql resolve queries \
              --search-path=./codeql \
              --additional-packs=./codeql \
              $suite
          done

      - name: Test Queries
        run: |
          if [ -d ./tests/${{ matrix.language }}-tests/ ]; then
          gh codeql test run --additional-packs=./ --additional-packs=./codeql ./tests/${{ matrix.language }}-tests/
          fi
